from pydantic import BaseModel, Field

from open_fin_gym.pipeline.config import Scope
from open_fin_gym.pipeline.db.tables import Paper


def build_paper_summary_prompt(
    scope: Scope,
    paper: Paper,
    excerpt: str,
) -> str:
    return f"""
## Your Task

You are designing a machine learning {scope.task_type} assessment based on the experiment(s) described in a science paper.

The specification of the task should consist of:

- A detailed description of the task to be undertaken
- A detailed description of any training input datasets
- A detailed description of any training target/ground-truth datasets
- A detailed description of any test input datasets
- A detailed description of the test output that should be generated by the use for assessment
- A detailed description of any test target/ground-truth data
- A detailed description of the assessment of the task, i.e. what metrics should be used, and how they are applied to the datasets

These descriptions will then be used to generate description files, and code to generate relevant datasets.

## Example

If the paper describes an experiment where they assessed their models ability to predict 7 days of a stock prices from a 30 day window
assessed on the MSE between the predicted and ground-truth prices, the specification could include:

- Description: The task is to implement a model that predicts the following 7 days of prices of a single stock, given the previous 30 days.
  You are provided with a training set consisting of a [M, 30] matrix of input windows, and corresponding [M, 7] target outputs. You are
  also provided with a [N, 30] set of test inputs and you should produce a [N, 7] matrix of outputs for assessment against the ground truth.
  The output of your model will be assessed using the MSE between your output and the ground-truth.
- Training input data:
    - x_train a [M, 30] matrix of M 30-day AAPL stock price windows randomly sampled from 2020
- Training target data:
    - y_train a [M, 7] target price windows following on from x_train
- Test input data:
    - x_test a [N, 30] matrix of N 30-day AAPL stock price windows randomly sampled from 2020
- Test output data:
    - y_pred a [N, 7] matrix of predicted prices for the 7 days following on from the provided x_test
- Test target data:
    - y_test a [N, 7] matrix of target price windows following on from x_test
- Assessment metrics:
    - MSE: The mean-squared-error between y_pred and y_test

## Notes

- These description you produce will then be used by downstream tasks to define the task, and write code to retrieve and save the datasets and assess the task.
- If the papers contain multiple experiments, select one to implement.
- The user will be provided with the task description and train input, train target, and test input datasets (holding out the assessment test target data). The
  user will write their output to a file, which will then be read and assessed using the task metrics.
- The dataset descriptions should be sufficiently detailed to allow a user to write a script to retrieve/download the data from public sources. Where possible
  use direct links found in the paper itself.

## Paper

Title: {paper.title}

{excerpt}
""".strip()


class Dataset(BaseModel):
    name: str = Field(description="ID of the dataset")
    filename: str = Field(description="Filename used to store the datasets")
    description: str = Field(
        description="Description of the dataset including its structure and how it is constructed"
    )
    source: str = Field(description="Where the data was sourced from")
    relevant_urls: list[str] = Field(
        description="URLs related to the dataset, e.g. download links"
    )
    download_link: str | None = Field(
        description="Optional dataset direct download link if available"
    )


class AssessmentMetric(BaseModel):
    name: str = Field(description="Name id assigned to the metric")
    description: str = Field(
        description="Description of the metric and how it applied to the users output"
    )
    input_datasets: list[str] = Field(
        description="List of dataset filenames that form the input to the metric"
    )


class PaperTaskSpecification(BaseModel):
    reasoning: str
    task_name: str = Field(description="Name id assigned to the task")
    task_description: str = Field(
        description="Description of the ML task including the data and how it is assessed"
    )
    training_inputs: list[Dataset] = Field(
        description="List of training input datasets"
    )
    training_targets: list[Dataset] = Field(
        description="List of training ground-truth/target datasets"
    )
    test_inputs: list[Dataset] = Field(description="List of test input datasets")
    test_targets: list[Dataset] = Field(
        description="List of ground truth datasets used to assess the users output against"
    )
    test_outputs: list[Dataset] = Field(
        description="List of test outputs files the user should produce"
    )
    assessment_metrics: list[AssessmentMetric] = Field(
        description="List of metrics used to assess the users output"
    )
